alias c='cmatrix -f -C red -s'
alias b='byobu'
alias cc='./console'
alias ip='wget http://ipinfo.io/ip -qO -'
alias t='tree -L 2'
alias tt='tree -L 3'
alias msi='msikeyboard -i high -c green  right red'
